### ISSUE TITLE
ImportError: dlopen: no suitable image found

### ISSUE THREAD

**Issue by mrabarnett** [mrabarnett/mrab-regex#429]
**[Original report](https://bitbucket.org/mrabarnett/mrab-regex/issue/429) by Den Avrondo (Bitbucket: [Den Avrondo](https://bitbucket.org/Den Avrondo), ).**

----------------------------------------

MacBook Air late 2020 M1. MacOS Big Sur 11.6. Installed using pip \(screenshot\). Getting error while importing.

‌

```
Traceback (most recent call last):
  File "/Users/lifr0m/PycharmProjects/John_Golt/django3/aggregators/BTC.py", line 16, in <module>
    from bundles.paymethods import *
  File "/Users/lifr0m/PycharmProjects/John_Golt/django3/bundles/paymethods.py", line 1, in <module>
    import regex as re
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so: code signature in (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so) not valid for use in process using Library Validation: Trying to load an unsigned library
```

‌

**Comment by mrabarnett** [comment]
Duplicate of issue #399. Now fixed.
