### ISSUE TITLE
Issue with 2021.10.8 on Mac OS Monterey (Beta) M1

### ISSUE THREAD

**Issue by mrabarnett** [mrabarnett/mrab-regex#432]
**[Original report](https://bitbucket.org/mrabarnett/mrab-regex/issue/432) by Anonymous.**

----------------------------------------

Hello, 
I faced this issue today for the first time. The problem appears when I am trying to run python file with nltk library:

```python

Traceback (most recent call last):
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/main.py", line 37, in <module>
    import nltk
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/nltk/__init__.py", line 133, in <module>
    from nltk.text import *
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/nltk/text.py", line 30, in <module>
    from nltk.tokenize import sent_tokenize
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/nltk/tokenize/__init__.py", line 66, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/nltk/tokenize/casual.py", line 38, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 0x0002): tried: '/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so' (code signature in <12C6F24E-1D7D-3A3B-BD5B-396F76DC371E> '/Users/alexeyshulzhenko/Documents/Projects/Personal/Proj. 8 - Crypto Notificator/venv/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so' not valid for use in process: Trying to load an unsigned library), '/usr/lib/_regex.cpython-39-darwin.so' (no such file)
```

UPD.

I was able to fix it by installing the older version of regex (that's why I opened this issue here)

```python

pip install regex==2021.8.28
```

**Comment by bruceadams** [comment]
This was fixed (at least worked around) by 26d37df1c3d0faa2a40098eb45b0300cfa0e8aa6. Releases after 2021.10.21 are working on macOS M1 machines.

**Comment by mrabarnett** [comment]
The question now is whether the latest wheels are working on MacOS M1 machines, now that they're being built by GitHub Actions.

**Comment by bruceadams** [comment]
Ah! ok.

Installing regex-2021.11.2 on an M1 MacBook Air (by installing the latest `black` and pulling in its latest dependencies) I see:

```
$ file _regex.cpython-39-darwin.so
_regex.cpython-39-darwin.so: Mach-O 64-bit bundle arm64
```

Running `black` with this regex works. So, a very basic smoke test looks good 🎉.

Is there any deeper testing you'd like to see?

**Comment by mrabarnett** [comment]
If the M1 problem is now fixed, I can now close this issue.
