### ISSUE TITLE
Scoped inline flags 'a', 'u' and 'L' affect global flags

### ISSUE THREAD

**Issue by serhiy-storchaka** [mrabarnett/mrab-regex#467]
```
>>> regex.match(r'\w\w', 'dж')
<regex.Match object; span=(0, 2), match='dж'>
>>> regex.match(r'(?a:\w)\w', 'dж')
>>> regex.compile(r'(?a:\w)\w')
regex.Regex('(?a:\\w)\\w', flags=regex.A | regex.V0)
>>> regex.compile(r'(?a:\w)\w', regex.UNICODE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/.local/lib/python3.8/site-packages/regex/regex.py", line 351, in compile
    return _compile(pattern, flags, ignore_unused, kwargs, _cache_all)
  File "/home/serhiy/.local/lib/python3.8/site-packages/regex/regex.py", line 544, in _compile
    raise ValueError("ASCII, LOCALE and UNICODE flags are mutually incompatible")
ValueError: ASCII, LOCALE and UNICODE flags are mutually incompatible
>>> regex.compile(r'(?a:\w)(?u:\w)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/.local/lib/python3.8/site-packages/regex/regex.py", line 351, in compile
    return _compile(pattern, flags, ignore_unused, kwargs, _cache_all)
  File "/home/serhiy/.local/lib/python3.8/site-packages/regex/regex.py", line 544, in _compile
    raise ValueError("ASCII, LOCALE and UNICODE flags are mutually incompatible")
ValueError: ASCII, LOCALE and UNICODE flags are mutually incompatible
```
Compare with `re`:
```
>>> re.match(r'(?a:\w)\w', 'dж')
<re.Match object; span=(0, 2), match='dж'>
>>> re.compile(r'(?a:\w)\w')
re.compile('(?a:\\w)\\w')
>>> re.compile(r'(?a:\w)\w', re.UNICODE)
re.compile('(?a:\\w)\\w')
```
Support for scoped inline flags was added in Python 3.6, but flags 'a', 'u' and 'L'  still could not be used as scoped. Since Python 3.7 they can be used as scoped flags.

**Comment by mrabarnett** [comment]
Fixed in regex 2022.4.24.
