### ISSUE TITLE
`VERBOSE`/`X` flag breaks `\N` escapes 

### ISSUE THREAD

**Issue by LyricLy** [mrabarnett/mrab-regex#527]
The `re` and `regex` modules recognize `\N` escapes for providing codepoints by their Unicode names. For example:
```python-console
>>> regex.compile(r"\N{LATIN SMALL LETTER A}").match("a")
<regex.Match object; span=(0, 1), match='a'>
```
However, passing the `regex.VERBOSE` flag seems to make these escapes stop working correctly, likely due to the spaces included in them. This is not consistent with the behaviour of `re`, which leaves these escapes untouched. Trying to escape the spaces inside the escape also seems to be unproductive.
```python-console
>>> regex.compile(r"\N{LATIN SMALL LETTER A}", regex.VERBOSE).match("a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lyricly/.local/lib/python3.12/site-packages/regex/regex.py", line 353, in compile
    return _compile(pattern, flags, ignore_unused, kwargs, cache_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyricly/.local/lib/python3.12/site-packages/regex/regex.py", line 542, in _compile
    raise error(caught_exception.msg, caught_exception.pattern,
regex._regex_core.error: undefined character name at position 24
>>> re.compile(r"\N{LATIN SMALL LETTER A}", re.VERBOSE).match("a")
<re.Match object; span=(0, 1), match='a'>
>>> regex.compile(r"\N{LATIN\ SMALL\ LETTER\ A}", regex.VERBOSE).match("a")
>>>
```

**Comment by mrabarnett** [comment]
Fixed in regex 2024.4.28.
